# Generated by Django 2.0.13 on 2019-08-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='description',
            new_name='card_description',
        ),
    ]
