# Generated by Django 2.0.13 on 2019-09-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='card_description',
            field=models.TextField(null=True),
        ),
    ]
