# Generated by Django 2.0.13 on 2019-08-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='owner',
        ),
    ]
