# Generated by Django 2.0.13 on 2019-09-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='card_img',
        ),
        migrations.AddField(
            model_name='cardimage',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.Card'),
        ),
    ]
