# Generated by Django 2.0.13 on 2019-08-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_remove_list_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='owner',
            new_name='author',
        ),
    ]
