# Generated by Django 2.0.13 on 2019-09-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_auto_20190909_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='InitialUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_user', models.CharField(max_length=200)),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.BoardMembers')),
            ],
        ),
    ]
