# Generated by Django 2.0.13 on 2019-08-21 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_remove_list_boardmember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardmembers',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
