# Generated by Django 2.0.13 on 2019-09-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0002_userprofile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardimage',
            name='card',
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='CardImage',
        ),
    ]
