# Generated by Django 2.0.13 on 2019-09-12 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_auto_20190911_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardimage',
            name='empty',
            field=models.BooleanField(default=False),
        ),
    ]
