# Generated by Django 2.0.13 on 2019-09-09 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0003_initialuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardInvite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_member', models.CharField(max_length=200)),
                ('board_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trello.BoardMembers')),
            ],
        ),
        migrations.RemoveField(
            model_name='initialuser',
            name='board_member',
        ),
        migrations.DeleteModel(
            name='InitialUser',
        ),
    ]
