# Generated by Django 2.0.13 on 2019-09-10 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_auto_20190909_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_title', models.CharField(max_length=200)),
                ('card_img', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
