# Generated by Django 2.0.13 on 2019-08-19 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0004_auto_20190819_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='list_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.List'),
        ),
        migrations.AddField(
            model_name='list',
            name='board_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Board'),
        ),
    ]
