# Generated by Django 2.0.13 on 2019-08-19 10:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trello', '0005_auto_20190819_1809'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='card',
            name='list_id',
        ),
        migrations.RemoveField(
            model_name='list',
            name='board_id',
        ),
        migrations.AddField(
            model_name='board',
            name='list_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.List'),
        ),
        migrations.AddField(
            model_name='card',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='updated_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='card_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Card'),
        ),
        migrations.AddField(
            model_name='boardmembers',
            name='board_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='trello.Board'),
        ),
    ]
